<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>eu.debooy.maven</groupId>
    <artifactId>pom</artifactId>
    <version>3.2.0</version>
  </parent>
  <groupId>eu.debooy.natuur</groupId>
  <artifactId>natuurtools</artifactId>
  <version>2.3.0</version>
  <packaging>jar</packaging>
  <name>Natuur Tools</name>
  <description>Verschillende Tools voor de 'Natuur' applicaties.</description>
  <inceptionYear>2020</inceptionYear>
  <scm>
    <connection>scm:git:ssh://ptah.debooy.eu/srv/local/devops/git/debooy/NatuurTools.git</connection>
    <developerConnection>scm:git:ssh://ptah.debooy.eu/srv/local/devops/git/debooy/NatuurTools.git</developerConnection>
    <tag>natuurtools-2.3.0</tag>
  </scm>

  <developers>
    <developer>
      <name>Marco de Booij</name>
      <id>booymar</id>
      <email>marco.developer@debooy.eu</email>
      <organization>dOOS</organization>
      <roles>
        <role>Project Manager</role>
        <role>Java Developer</role>
      </roles>
    </developer>
  </developers>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.openjpa</groupId>
        <artifactId>openjpa-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>2.3</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>eu.debooy.natuurtools.NatuurTools</mainClass>
                </transformer>
              </transformers>
              <filters>
                <filter>
                  <artifact>eu.debooy.natuur:natuur-components</artifact>
                  <excludes>
                    <exclude>persistence.xml</exclude>
                  </excludes>
                </filter>
              </filters>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>eu.debooy.doosutils</groupId>
      <artifactId>doosutils-test</artifactId>
      <version>2.1.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>eu.debooy.natuur</groupId>
      <artifactId>natuur-components</artifactId>
      <version>5.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.openjpa</groupId>
      <artifactId>openjpa</artifactId>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
  </dependencies>
</project>
